# Manipulación de los datos

## Recopilación de datos

In [3]:
import pandas as pd

url = "https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv"

pd.read_csv(url)

datos = pd.read_csv(url, delimiter=";")
datos

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

## Crear columnas numéricas
El equipo de desarrollo del sitio web de la empresa solicitó la creación de dos nuevas columnas numéricas en nuestra base de datos. En el sitio web de las propiedades, desean presentar información más resumida en relación a los valores. Para esto, estas columnas serán importantes:

valor_mensual: Esta columna debe contener los gastos mensuales de cada propiedad, incluyendo el alquiler y el condominio.

valor_anual: Esta columna debe contener los gastos anuales por propiedad, es decir, el Impuesto más 12 meses de alquiler y condominio.

1. valor_mensual: Esta columna debe contener los gastos mensuales de cada propiedad, incluyendo el alquiler y el condominio.

In [4]:
# Creación de columna a partir de una operación matemática
datos['Valor_mensual'] = datos['Valor'] + datos['Condominio']
datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto,Valor_mensual
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0,7700.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5,32270.0
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0,4165.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN,3605.0

2. valor_anual: Esta columna debe contener los gastos anuales por propiedad, es decir, el Impuesto más 12 meses de alquiler y condominio.

In [7]:
datos['Valor_anual'] = 12*datos['Valor_mensual'] + datos['Impuesto']
datos.tail()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto,Valor_mensual,Valor_anual
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5,4025.0,48387.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5,6681.5,80307.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN,13160.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5,37471.0,453533.5

## Creando columna Descripción
El equipo de desarrollo solicitó la creación de dos columnas adicionales. Sin embargo, esta vez son categóricas:

- Descripcion: Esta columna debe contener un resumen de la información clave de las propiedades que se mostrarán en el sitio web: tipo de propiedad, barrio, cantidad de habitaciones y plazas de estacionamiento.
- Tiene_suite: Esta debe ser una columna que indique únicamente si la propiedad tiene o no suites, sin importar la cantidad.

1. Columna Descripcion

In [ ]:
datos['Descripcion'] = datos['Tipo'] + ' en la colonia ' + datos['Colonia'] + \
                      ' con ' + datos['Habitaciones'].astype(str) + ' habitacion/es y ' \
                      + datos['Garages'].astype(str) + ' plazas de estacionamiento.'
datos.head(1).Descripcion

0    Cocineta en la colonia Condesa con 1 habitacio...
Name: Descripcion, dtype: object

2. Columna Tiene_suite

In [29]:
# Se aplicará una función anónima a la columna 'Suites'
datos['Tiene_suite'] = datos['Suites'].apply(lambda x: 'Si' if x > 0 else 'No')
datos.sample(10)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto,Valor_mensual,Valor_anual,Descripcion,Tiene_suite
4658,Casa de Condominio,Santa Fe,4,3,4,350,31500.0,3269.0,31027.5,34769.0,448255.5,Casa de Condominio en la colonia Santa Fe con ...,Si
24096,Conjunto Comercial/Sala,Centro Histórico,0,0,0,629,110075.0,55937.0,5281.5,166012.0,1997425.5,Conjunto Comercial/Sala en la colonia Centro H...,No
2509,Tienda/Salón,Centro Histórico,0,0,0,25,1750.0,1925.0,315.0,3675.0,44415.0,Tienda/Salón en la colonia Centro Histórico co...,No
2722,Departamento,Villa Coapa,2,1,0,50,2800.0,955.5,NaN,3755.5,NaN,Departamento en la colonia Villa Coapa con 2 h...,No
18554,Departamento en Hotel,Coyoacán,1,0,0,46,21000.0,NaN,NaN,NaN,NaN,Departamento en Hotel en la colonia Coyoacán c...,No
21609,Departamento,Del Valle,2,0,0,98,7700.0,2831.5,NaN,10531.5,NaN,Departamento en la colonia Del Valle con 2 hab...,No
21768,Departamento,Condesa,4,1,2,225,28000.0,6650.0,NaN,34650.0,NaN,Departamento en la colonia Condesa con 4 habit...,Si
9227,Tienda/Salón,San Sebastián,0,0,0,200,70000.0,14000.0,NaN,84000.0,NaN,Tienda/Salón en la colonia San Sebastián con 0...,No
12297,Casa de Condominio,Peralvillo,2,0,1,68,5250.0,1260.0,140.0,6510.0,78260.0,Casa de Condominio en la colonia Peralvillo co...,Si
21097,Departamento,Lomas de Chapultepec,3,1,0,82,11550.0,3850.0,7700.0,15400.0,192500.0,Departamento en la colonia Lomas de Chapultepe...,No

In [30]:
datos.to_csv('exported-data/inmuebles_dev.csv', index=False, sep=';')